### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by simon1066** [torvista/Zen-Cart_Multiple-Products-Copy-Move-Delete#2]
Existing version: does not copy product meta tags (tested using 'Copy as NEW Duplicate Products').

**Comment by torvista** [comment]
ok.

**Comment by torvista** [comment]
no, still not done..

**Comment by torvista** [comment]
For Copy-Duplicate it copies all aspects as per selected....when used with the ZC157 version of admin/modules/product_copy_confirm.php
