### ISSUE TITLE
Message issued on login page

### ISSUE THREAD

**Issue by lat9** [torvista/Zen-Cart_Multiple-Products-Copy-Move-Delete#5]
I wasn't logged in when I applied the plugin's files to my test site, and I received the update notice on the login page.  Was this to be expected?

![image](https://user-images.githubusercontent.com/2685585/72153498-2bade780-337c-11ea-880c-6ba6e2035aa8.png)

**Comment by torvista** [comment]
At the moment yes this bit is unresolved, due to this:
https://github.com/zencart/zencart/issues/2979

It's currently just spitting it out into the ether willy nilly.

**Comment by lat9** [comment]
If you change that menu-addition to an init_include, the message-stack has been established (as is the session) so that you can check to see if an admin is logged in before setting that message.

**Comment by torvista** [comment]
ok, done that.
