### ISSUE TITLE
moving products within subcats

### ISSUE THREAD

**Issue by lankeeyankee** [torvista/Zen-Cart_Multiple-Products-Copy-Move-Delete#6]
possible bug in 1.5.6c. Moving products to a new master category, selecting a parent category to search with the search subcategory box checked. It correctly returns everything in the subcategories in the result. When clicking "toggle all" to move, then confirming, it give the success message but does not actually move them. Everything stays as it was. This works as expected when moving from bottom-level cats that actually hold products, just not higher level cats with subcats included.

**Comment by torvista** [comment]
thanks...don't hold your breath....

**Comment by lankeeyankee** [comment]
Sorry, I didn't check first if there was a more recent version. I will update the files and try again and report back

**Comment by lankeeyankee** [comment]
same result with latest files from repo

**Comment by torvista** [comment]
ok, try that.

**Comment by lankeeyankee** [comment]
Thanks! I tried to move all products within multiple subcats, toggling them all, and get an error Array of products found and array count not equal. which according to the code comment should never happen :-)

**Comment by torvista** [comment]
is this a real shop or a ZC vanilla?

**Comment by lankeeyankee** [comment]
tested on a different set of cats/subcats and it does work. Not sure why my first one didn't work, I am looking at it further, don't see any linked within the subcats

**Comment by lankeeyankee** [comment]
real shop

**Comment by lankeeyankee** [comment]
It was 598 products in total. Is there a limit for array sizes? I am able to move 339 from a group of those subcats without issue. I tried on a different cat/subcat group with 1079 products and get the same error. 

I am on a dedicated server with 16GB RAM, I am not getting any server logs or zc debug logs so it's not a memory issue.

I put in a sprintf to show what $cnt is and count($found) is after clicking confirm. It shows the correct counts on smaller moves, "counted: 339, found: 339". When trying the larger moves it's "counted: 0, found: 1"

**Comment by torvista** [comment]
I wonder if it is going awry as you are going over the php limit for max_input_vars...which limits the POST array from which this bit is derived.

**Comment by lankeeyankee** [comment]
That must be it. I have been tinkering trying to find the upper limit. I just moved 488 successfully, but couldn't get 495 to move.

**Comment by lankeeyankee** [comment]
That was it. When I up the max_input_variables I can move more. It needs to be twice as many as the products needing to be moved. So might want to include something in the error message that this could be the issue and check server's php.ini.

**Comment by torvista** [comment]
Yes, I have that in the P2C manager.

**Comment by torvista** [comment]
The limit is actually max_input_vars/2-10.
After exploring several scenarios of limiting checkbox selection etc., I think the best way to handle it is to limit the search results to this number (with a message) and so toggle all will work.
It's not a great hardship to do this multiple times in the unlikely case of moving so many products, rather than facing error messages.
