### ISSUE TITLE
array error 

### ISSUE THREAD

**Issue by OldNGreyBMR** [torvista/Zen-Cart_Multiple-Products-Copy-Move-Delete#7]
Scenario 1: Select multiple products to move from sub category to another sub category. 
Confirm -> crashes ZC with error log "Cannot use object of type queryFactoryResult as array in admin\multiple_product_copy.php:595"

Scenario 2:  3 products in a sub- category A selected to move to another sub-category B
select all 3 product; confirm; only one is moved
repeat selection; select all 2; confirm; only one is moved

Scenario 3: search for product using wild card "air%filter%"; 15 products returned; select all; confirm -> crash (http error 500)
error log same as scenario 1

environment Dev: Zen Cart 157; Apache 2.4.46; PHP 7.3.21; MySQL 5.7.31; Windows 10

**Comment by torvista** [comment]
ZC157 vanilla and using the files from this Github. Windows 10 (xampp) php 7.4.5
I note the modules/product_copy_confirm and move_product_confirm in this fileset are not updated to match the ZC157 versions, but I used these ones for now.

I moved dvd videos between subcategories with no problem.
What do you have on line 595?

What is the difference between scenario 1 ("multiple") and 2 (3 selected)?

**Comment by OldNGreyBMR** [comment]
1. Scenarios. In the dim past one version would not move all files but would work with only a few selected.
2. My files have been copied from this site. Line 595 is the same
 590                if ($copy_as === 'move') { //if product found
591                    $action = 'multiple_product_copy_return'; // used in move_product_confirm.php (core modification required) to prevent default redirect and so allow multiple moves
592                    $_POST['products_id'] = $id; // for move_product_confirm
593                    $_POST['move_to_category_id'] = $target_category_id;// for move_product_confirm
594                    if ($search_category_id === 0) { // 0: search all categories: use the product's master category id as the search/source category
595                        $current_category_id = $found_product['master_categories_id'];// $current_category_id used by move_product_confirm to reset master_category_id
596                    } else { // a search category is set: the products therein may be linked or master
597                        $current_category_id = $categories_selected[$key];
598                    }
=============
I get the same result in a Vanilla 157 with my data loaded.

**Comment by torvista** [comment]
I can't reproduce this.
Could you put an instance of this on some test server that I can access by ftp?

I don't see private messages on Github so send details through pm on the forum.

**Comment by OldNGreyBMR** [comment]
i don't have one set up to face externally . Can you provide copies of the
exact files you have used? i can try again on a vanilla install as i copied
the code from github by copy and paste which may have introduced an error.

**Comment by torvista** [comment]
PM sent with complete Admin files.

**Comment by OldNGreyBMR** [comment]
I am using your set of admin files and using the vanilla default data and still receive error messages.
This example is from copy product as linked
target: CDROM drives
keyword: time
preview returns 5 items; ID 158 twice; ID 23 three times
toggle all
result: screen error + log file error
one record of ID 158 is linked to CDROM drives category
- - - - - - - - -
screen error : 'WARNING: An Error occurred, please refresh the page and try again.If you were entering information, press the BACK button in your browser and re-check the information you had entered to be sure you left no blank fields."
- - - - - - - - 
log file error
```
23-Oct-2020 21:26:07 UTC] Request URI: /zc157_vanilla/admin/index.php?cmd=multiple_product_copy&action=confirm, IP address: 192.168.1.63
#1  trigger_error() called at [\zc157_vanilla\includes\classes\db\mysql\query_factory.php:170]
#2  queryFactory->show_error() called at [\zc157_vanilla\includes\classes\db\mysql\query_factory.php:142]
#3  queryFactory->set_error() called at [\zc157_vanilla\includes\classes\db\mysql\query_factory.php:269]
#4  queryFactory->Execute() called at [\zc157_vanilla\includes\functions\database.php:44]
#5  zen_db_perform() called at [\zc157_vanilla\admin\multiple_product_copy.php:521]
#6  require(\zc157_vanilla\admin\multiple_product_copy.php) called at [\zc157_vanilla\admin\index.php:11]
--> PHP Fatal error: 1062:Duplicate entry '158-17' for key 'PRIMARY' :: INSERT INTO zen_products_to_categories (products_id, categories_id) VALUES ('158', '17') ==> (as called by) \zc157_vanilla\includes\functions\database.php on line 44 <== in \zc157_vanilla\includes\classes\db\mysql\query_factory.php on line 170.
```
- -  - - - -
dashed lines create huge font - edited to remove the dashed lines

**Comment by OldNGreyBMR** [comment]
Separate github issue  how do I reduce the font size in the comments?

**Comment by torvista** [comment]
ok, I see it. It's the keyword that causes it....

**Comment by torvista** [comment]
Try this, 
Look for
```
            WHERE p.products_id = pd.products_id 
            AND p.products_id = ptoc.products_id 
            AND pd.language_id =  ' . (int)$_SESSION['languages_id'];
```
and change it to

```
WHERE p.products_id = pd.products_id 
            AND p.products_id = ptoc.products_id 
            AND pd.language_id =  ' . (int)$_SESSION['languages_id'] . ' 
            AND p.master_categories_id = ptoc.categories_id';
```
It'll fix the search, but not sure about the other options as it's way past my bed-time....

**Comment by torvista** [comment]
I've pushed a better solution which modifies the sql for that option only.

**Comment by OldNGreyBMR** [comment]
Very good. Copy products works

**Comment by OldNGreyBMR** [comment]
Copy products as duplicates fails and produces the following error log listed below. 
This is due to 'TEXT_DUPLICATE_IDENTIFIER' being undefined. If I check its existence and define it at the beginning of multiple_product_copy.php the duplication completes.
The duplicate source records are written to the same target record
- - - 
` Linked Category ID#70 copied from Product ID#3827 to duplicate Product ID#4107  
 Linked Category ID#124 copied from Product ID#3827 to duplicate Product ID#4107 
 Discounts copied from Product ID#3827 to duplicate Product ID#4107
`
- - - - 
`if (defined('TEXT_DUPLICATE_IDENTIFIER')&&!empty(TEXT_DUPLICATE_IDENTIFIER)) {
	define('TEXT_DUPLICATE_IDENTIFIER', '[DUPLICATE]');`
- - - - 
`[25-Oct-2020` 21:50:12 UTC] Request URI: /zc157_vanilla/admin/index.php?cmd=multiple_product_copy&action=confirm, IP address: 192.168.1.63
#1  trigger_error() called at [E:\Web\zc157_vanilla\includes\classes\db\mysql\query_factory.php:170]
#2  queryFactory->show_error() called at [E:\Web\zc157_vanilla\includes\classes\db\mysql\query_factory.php:142]
#3  queryFactory->set_error() called at [E:\Web\zc157_vanilla\includes\classes\db\mysql\query_factory.php:269]
#4  queryFactory->Execute() called at [E:\Web\zc157_vanilla\admin\includes\modules\copy_product_confirm.php:116]
#5  require(E:\Web\zc157_vanilla\admin\includes\modules\copy_product_confirm.php) called at [E:\Web\zc157_vanilla\admin\multiple_product_copy.php:537]
#6  require(E:\Web\zc157_vanilla\admin\multiple_product_copy.php) called at [E:\Web\zc157_vanilla\admin\index.php:11]
--> PHP Fatal error: 1406:Data too long for column 'products_name' at row 1 :: INSERT INTO zen_products_description (products_id, language_id, products_name, products_description, products_url)
                    VALUES ('4106',
                            '1',
                            'Air filter assembly, twin carb, Norton Commando TEXT_DUPLICATE_IDENTIFIER',
                            '<p><b>Air filter / cleaner&nbsp; assembly for Norton Commando with twin carbs, unpainted stainless steel</b><br />\r\nOriginal part number:<br />\r\n050742- air filter assembly<br />\r\n1 x front plate (2 carbs) - 062266s<br />\r\n1 x back plate - 062799s<br />\r\n1 x gauze - 060816s<br />\r\n1 x element - 060673<br />\r\n2 x gaiters - 062537<br />\r\n1 set bolts - 060900s<br />\r\n2 x bolt &frac14; unf x &frac12; - 068075s<br />\r\n4 x washer - 050241<br />\r\n1 x nyloc nut - 067971s<br />\r\n1 x tab washer - 060926<br />\r\n1 x spacer - 062170s<br />\r\n1 x hex screw &frac14; x &frac34; unf - 050571</p>',
                            ''
                            ) ==> (as called by) E:\Web\zc157_vanilla\admin\includes\modules\copy_product_confirm.php on line 116 <== in E:\Web\zc157_vanilla\includes\classes\db\mysql\query_factory.php on line 170.`

**Comment by torvista** [comment]
You may need to add the same clause around the other place(s) where TEXT_DUPLICATE_IDENTIFIER is defined, and regarding the too long error:
https://github.com/zencart/zencart/pull/4017

So, all is working now?

**Comment by OldNGreyBMR** [comment]
only copy products as linked works.
Copy products as duplicates 
writes tries to write all source records to the same target record eg 3 distinct records selected but only one new record is created as a counter is not incremented somewhere.

**Comment by torvista** [comment]
I don't get a problem with copy as duplicate.
I've just updated the files with latest ZC158 changes but that should not be relevant to this.
Can you describe the procedure to failure?

**Comment by OldNGreyBMR** [comment]
With copy as duplicate it only duplicates the first record selected.
4 records selected

```
	1020	Air filter, element, Norton Commando	BT-060673 (R-060673)	Air filter, element, Norton Commando	Carburettor > Carb-General ID#70
	4109	Air filter, element, Norton Commando TEXT_DUPLICATE_IDENTIFIER	BT-060673 (R-060673)	Air filter, element, Norton Commando TEXT_DUPLICATE_IDENTIFIER	Carburettor > Carb-AMAC ID#162
	4110	Air filter, element, Norton Commando TEXT_DUPLICATE_IDENTIFIER	BT-060673 (R-060673)	Air filter, element, Norton Commando TEXT_DUPLICATE_IDENTIFIER	Carburettor > Carb-AMAC ID#162
	4111	Air filter, element, Norton Commando [COPY]	BT-060673 (R-060673)	Air filter, element, Norton Commando [COPY]	Carburettor > Carb-AMAC ID#162
```
Resulting msg at top of page:
```
	Linked Category ID#70 copied from Product ID#1020 to duplicate Product ID#4116
	Linked Category ID#124 copied from Product ID#1020 to duplicate Product ID#4116
	Linked Category ID#162 copied from Product ID#1020 to duplicate Product ID#4116
	Discounts copied from Product ID#1020 to duplicate Product ID#4116
```
In target folder only the first record is duplicated 
`4116	Preview	Air filter, element, Norton Commando [DUP]	BT-060673 (R-060673)	`

**Comment by OldNGreyBMR** [comment]
Copy as duplicate works!
I am now using the file 'copy_product_confirm.157a php".
The only change required is to truncate the product name to 64 chars before writing to the database.

**Comment by OldNGreyBMR** [comment]
Move products work sometimes.
If I select all products, in this case 51, I get the error 
`PHP Fatal error: Uncaught Error: Cannot use object of type queryFactoryResult as array in E:\Web\zc157_vanilla\admin\multiple_product_copy.php:605`
The code is
`// bof: move from one category to another
600                if ($copy_as === 'move') { //if product found
601                    $action = 'multiple_product_copy_return'; // used in move_product_confirm.php (core modification required) to prevent default redirect and so allow multiple moves
602                    $_POST['products_id'] = $id; // for move_product_confirm
603                    $_POST['move_to_category_id'] = $target_category_id;// for move_product_confirm
604                    if ($search_category_id === 0) { // 0: search all categories: use the product's master category id as the search/source category
605                        $current_category_id = $found_product['master_categories_id'];// $current_category_id used by move_product_confirm to reset master_category_id
                    } else { // a search category is set: the products therein may be linked or master
                        $current_category_id = $categories_selected[$key];`

**Comment by OldNGreyBMR** [comment]
Move works consistently without errors.
Near the beginning of  admin\multiple_product_copy.php if have:
` if (!defined('TEXT_DUPLICATE_IDENTIFIER')) { 
    define('TEXT_DUPLICATE_IDENTIFIER', '[DUP]');}
  else {
    if (defined('TEXT_DUPLICATE_IDENTIFIER')&&!empty(TEXT_DUPLICATE_IDENTIFIER)) {
      define('TEXT_DUPLICATE_IDENTIFIER', '[DUP]');}
     }`
and on line 605 I changed
 `$current_category_id = $found_product['master_categories_id']; ` TO 
`$current_category_id = $found_product->fields['master_categories_id'];`
- - - - -
in admin\include\modules\copy_product_confirm.php
at line 119 before the insert into TABLE_PRODUCTS_DESCRIPTION I truncate the products_name to 55 chars
`$description['products_name'] = substr($description['products_name'],0,55);`
so the appending of the TEXT_DUPLICATE_IDENTIFIER doesn't exceed the product _name length of 64 chars
- - - - - 

I'll keep testing but it is looking very good.

**Comment by torvista** [comment]
I'm confused, this package works as is, or you are needed to make modifications?

**Comment by torvista** [comment]
Note that the copy of copy product confirm already has code in it to truncate the name from line 116

**Comment by OldNGreyBMR** [comment]
I'm just trying to get the  package to work without errors. I cannot see any obvious truncation code in copy_product_confirm. If you want to point me to new  set of files for the package. I'll download those and test them.

**Comment by torvista** [comment]
There is this bit in product copy confirm

> 	    //bof ZC158
>             $name = TEXT_DUPLICATE_IDENTIFIER . " " . zen_db_input($description['products_name']); 
>             $maxlen = zen_field_length(TABLE_PRODUCTS_DESCRIPTION, 'products_name'); 
>             if (strlen($name) > $maxlen) {
>                $name = substr($name, 0, $maxlen-1); 
>             }
> 	    //eof

**Comment by OldNGreyBMR** [comment]
I kept the TEXT_DUPLICATE_IDENTIFIER at the end and truncated the $description['products_name' before appending the TEXT_DUPLICATE_IDENTIFIER. 
This keeps the names in alpha order in display lists
Your setting of $maxlen to defined field size is smarter so I have incorporated that into my version.
```
// truncation bof
   $maxlen = zen_field_length(TABLE_PRODUCTS_DESCRIPTION, 'products_name'); 
   $description['products_name'] = substr(zen_db_input($description['products_name']),0,($maxlen - (strlen(TEXT_DUPLICATE_IDENTIFIER)+1)));
//  eof
            $db->Execute("INSERT INTO " . TABLE_PRODUCTS_DESCRIPTION . " (products_id, language_id, products_name, products_description, products_url)
                    VALUES ('" . $dup_products_id . "',
                            '" . (int)$description['language_id'] . "',
                            '" . zen_db_input($description['products_name']) . " " . TEXT_DUPLICATE_IDENTIFIER . "',
                            '" . zen_db_input($description['products_description']) . "',
                            '" . zen_db_input($description['products_url']) . "'
                            )");
        }

```

**Comment by torvista** [comment]
So, all is working?

**Comment by OldNGreyBMR** [comment]
All is working with the exception of Delete Linked Products.  When this option is selected the items in the returned set are all preceded by a check box filled with a red X. There is no way to select them.

The other two delete options: Delete Specials from Products; and Delete Any Products
both appear to work correctly.

**Comment by torvista** [comment]
>the returned set are all preceded by a check box filled with a red X

That means the product in the selected category is in it's master category/is not linked from elsewhere: so you are prevented from deleting it.
Can you detail a process when this is not true?

**Comment by OldNGreyBMR** [comment]
So this section can never work as only the products that have the selected category as the master category are returned. A product that is linked to the selected category is not returned in the search list results.

**Comment by torvista** [comment]
I used Copy as Linked to copy products from DVDs to CDROM.
I used Delete Linked with the CD-ROM category to delete the linked DVDs.
Search will only return products in their master categories, so no they cannot be deleted: if they returned all, in my case it would returns 1000's of links.
So, not a bug, but a feature that needs more thought....

**Comment by torvista** [comment]
posted a fix...hopefully nothing else is broken now!

**Comment by OldNGreyBMR** [comment]
That worked.
I had to copy the entire file as the code you updated was different ( in that sub-section) to the version that I was using, from the files provided 21 October.
